title: Blog Reporting Jasper
description: Construire un Blog Jekyll en quelques minutes, sans utilisation de la ligne de commandes .
google_analytics: 
show_downloads: true
theme: jekyll-theme-slate

gems:
  - jekyll-mentions
